# Generated by Django 5.1 on 2024-08-10 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ref', models.CharField(blank=True, max_length=255, null=True)),
                ('sn', models.CharField(blank=True, max_length=255, null=True)),
                ('sn_rempl', models.CharField(blank=True, max_length=255, null=True)),
                ('reception_date', models.DateField(blank=True, null=True)),
                ('delivery_status', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('bl', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('quarter', models.CharField(blank=True, max_length=2, null=True)),
                ('order_index', models.PositiveIntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='inventory.record')),
            ],
        ),
    ]
